import React, { HTMLAttributes } from 'react';
type Props<TTag extends keyof JSX.IntrinsicElements> = HTMLAttributes<TTag> & {
    children: React.ReactNode;
    /** Determines whether drag functionality is enabled, defaults to true */
    allowDrag?: boolean;
    /** Called when the user finishes a sorting gesture. */
    onSortEnd: (oldIndex: number, newIndex: number) => void;
    /** Class applied to the item being dragged */
    draggedItemClassName?: string;
    /** Determines which type of html tag will be used for a container element */
    as?: TTag;
    /** Determines if an axis should be locked */
    lockAxis?: 'x' | 'y';
    /** Reference to the Custom Holder element */
    customHolderRef?: React.RefObject<HTMLElement | null>;
};
declare const SortableList: <TTag extends keyof JSX.IntrinsicElements = "div">({ children, allowDrag, onSortEnd, draggedItemClassName, as, lockAxis, customHolderRef, ...rest }: Props<TTag>) => React.ReactElement<{
    ref: React.MutableRefObject<HTMLElement>;
    defaultChecked?: boolean;
    defaultValue?: string | number | readonly string[];
    suppressContentEditableWarning?: boolean;
    suppressHydrationWarning?: boolean;
    accessKey?: string;
    autoCapitalize?: "none" | (string & {}) | "words" | "off" | "on" | "sentences" | "characters";
    autoFocus?: boolean;
    className?: string;
    contentEditable?: "inherit" | (boolean | "false" | "true") | "plaintext-only";
    contextMenu?: string;
    dir?: string;
    draggable?: boolean | "false" | "true";
    enterKeyHint?: "search" | "next" | "done" | "enter" | "go" | "previous" | "send";
    hidden?: boolean;
    id?: string;
    lang?: string;
    nonce?: string;
    slot?: string;
    spellCheck?: boolean | "false" | "true";
    style?: React.CSSProperties;
    tabIndex?: number;
    title?: string;
    translate?: "yes" | "no";
    radioGroup?: string;
    role?: React.AriaRole;
    about?: string;
    content?: string;
    datatype?: string;
    inlist?: any;
    prefix?: string;
    property?: string;
    rel?: string;
    resource?: string;
    rev?: string;
    typeof?: string;
    vocab?: string;
    autoCorrect?: string;
    autoSave?: string;
    color?: string;
    itemProp?: string;
    itemScope?: boolean;
    itemType?: string;
    itemID?: string;
    itemRef?: string;
    results?: number;
    security?: string;
    unselectable?: "off" | "on";
    inputMode?: "search" | "numeric" | "none" | "url" | "text" | "decimal" | "tel" | "email";
    is?: string;
    exportparts?: string;
    part?: string;
    "aria-activedescendant"?: string;
    "aria-atomic"?: boolean | "false" | "true";
    "aria-autocomplete"?: "inline" | "both" | "none" | "list";
    "aria-braillelabel"?: string;
    "aria-brailleroledescription"?: string;
    "aria-busy"?: boolean | "false" | "true";
    "aria-checked"?: boolean | "false" | "mixed" | "true";
    "aria-colcount"?: number;
    "aria-colindex"?: number;
    "aria-colindextext"?: string;
    "aria-colspan"?: number;
    "aria-controls"?: string;
    "aria-current"?: boolean | "location" | "time" | "false" | "page" | "true" | "step" | "date";
    "aria-describedby"?: string;
    "aria-description"?: string;
    "aria-details"?: string;
    "aria-disabled"?: boolean | "false" | "true";
    "aria-dropeffect"?: "link" | "none" | "copy" | "move" | "execute" | "popup";
    "aria-errormessage"?: string;
    "aria-expanded"?: boolean | "false" | "true";
    "aria-flowto"?: string;
    "aria-grabbed"?: boolean | "false" | "true";
    "aria-haspopup"?: boolean | "grid" | "dialog" | "menu" | "false" | "listbox" | "true" | "tree";
    "aria-hidden"?: boolean | "false" | "true";
    "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling";
    "aria-keyshortcuts"?: string;
    "aria-label"?: string;
    "aria-labelledby"?: string;
    "aria-level"?: number;
    "aria-live"?: "off" | "assertive" | "polite";
    "aria-modal"?: boolean | "false" | "true";
    "aria-multiline"?: boolean | "false" | "true";
    "aria-multiselectable"?: boolean | "false" | "true";
    "aria-orientation"?: "horizontal" | "vertical";
    "aria-owns"?: string;
    "aria-placeholder"?: string;
    "aria-posinset"?: number;
    "aria-pressed"?: boolean | "false" | "mixed" | "true";
    "aria-readonly"?: boolean | "false" | "true";
    "aria-relevant"?: "all" | "text" | "additions" | "additions removals" | "additions text" | "removals" | "removals additions" | "removals text" | "text additions" | "text removals";
    "aria-required"?: boolean | "false" | "true";
    "aria-roledescription"?: string;
    "aria-rowcount"?: number;
    "aria-rowindex"?: number;
    "aria-rowindextext"?: string;
    "aria-rowspan"?: number;
    "aria-selected"?: boolean | "false" | "true";
    "aria-setsize"?: number;
    "aria-sort"?: "none" | "other" | "ascending" | "descending";
    "aria-valuemax"?: number;
    "aria-valuemin"?: number;
    "aria-valuenow"?: number;
    "aria-valuetext"?: string;
    dangerouslySetInnerHTML?: {
        __html: string | TrustedHTML;
    };
    onCopy?: React.ClipboardEventHandler<TTag>;
    onCopyCapture?: React.ClipboardEventHandler<TTag>;
    onCut?: React.ClipboardEventHandler<TTag>;
    onCutCapture?: React.ClipboardEventHandler<TTag>;
    onPaste?: React.ClipboardEventHandler<TTag>;
    onPasteCapture?: React.ClipboardEventHandler<TTag>;
    onCompositionEnd?: React.CompositionEventHandler<TTag>;
    onCompositionEndCapture?: React.CompositionEventHandler<TTag>;
    onCompositionStart?: React.CompositionEventHandler<TTag>;
    onCompositionStartCapture?: React.CompositionEventHandler<TTag>;
    onCompositionUpdate?: React.CompositionEventHandler<TTag>;
    onCompositionUpdateCapture?: React.CompositionEventHandler<TTag>;
    onFocus?: React.FocusEventHandler<TTag>;
    onFocusCapture?: React.FocusEventHandler<TTag>;
    onBlur?: React.FocusEventHandler<TTag>;
    onBlurCapture?: React.FocusEventHandler<TTag>;
    onChange?: React.FormEventHandler<TTag>;
    onChangeCapture?: React.FormEventHandler<TTag>;
    onBeforeInput?: React.InputEventHandler<TTag>;
    onBeforeInputCapture?: React.FormEventHandler<TTag>;
    onInput?: React.FormEventHandler<TTag>;
    onInputCapture?: React.FormEventHandler<TTag>;
    onReset?: React.FormEventHandler<TTag>;
    onResetCapture?: React.FormEventHandler<TTag>;
    onSubmit?: React.FormEventHandler<TTag>;
    onSubmitCapture?: React.FormEventHandler<TTag>;
    onInvalid?: React.FormEventHandler<TTag>;
    onInvalidCapture?: React.FormEventHandler<TTag>;
    onLoad?: React.ReactEventHandler<TTag>;
    onLoadCapture?: React.ReactEventHandler<TTag>;
    onError?: React.ReactEventHandler<TTag>;
    onErrorCapture?: React.ReactEventHandler<TTag>;
    onKeyDown?: React.KeyboardEventHandler<TTag>;
    onKeyDownCapture?: React.KeyboardEventHandler<TTag>;
    onKeyPress?: React.KeyboardEventHandler<TTag>;
    onKeyPressCapture?: React.KeyboardEventHandler<TTag>;
    onKeyUp?: React.KeyboardEventHandler<TTag>;
    onKeyUpCapture?: React.KeyboardEventHandler<TTag>;
    onAbort?: React.ReactEventHandler<TTag>;
    onAbortCapture?: React.ReactEventHandler<TTag>;
    onCanPlay?: React.ReactEventHandler<TTag>;
    onCanPlayCapture?: React.ReactEventHandler<TTag>;
    onCanPlayThrough?: React.ReactEventHandler<TTag>;
    onCanPlayThroughCapture?: React.ReactEventHandler<TTag>;
    onDurationChange?: React.ReactEventHandler<TTag>;
    onDurationChangeCapture?: React.ReactEventHandler<TTag>;
    onEmptied?: React.ReactEventHandler<TTag>;
    onEmptiedCapture?: React.ReactEventHandler<TTag>;
    onEncrypted?: React.ReactEventHandler<TTag>;
    onEncryptedCapture?: React.ReactEventHandler<TTag>;
    onEnded?: React.ReactEventHandler<TTag>;
    onEndedCapture?: React.ReactEventHandler<TTag>;
    onLoadedData?: React.ReactEventHandler<TTag>;
    onLoadedDataCapture?: React.ReactEventHandler<TTag>;
    onLoadedMetadata?: React.ReactEventHandler<TTag>;
    onLoadedMetadataCapture?: React.ReactEventHandler<TTag>;
    onLoadStart?: React.ReactEventHandler<TTag>;
    onLoadStartCapture?: React.ReactEventHandler<TTag>;
    onPause?: React.ReactEventHandler<TTag>;
    onPauseCapture?: React.ReactEventHandler<TTag>;
    onPlay?: React.ReactEventHandler<TTag>;
    onPlayCapture?: React.ReactEventHandler<TTag>;
    onPlaying?: React.ReactEventHandler<TTag>;
    onPlayingCapture?: React.ReactEventHandler<TTag>;
    onProgress?: React.ReactEventHandler<TTag>;
    onProgressCapture?: React.ReactEventHandler<TTag>;
    onRateChange?: React.ReactEventHandler<TTag>;
    onRateChangeCapture?: React.ReactEventHandler<TTag>;
    onSeeked?: React.ReactEventHandler<TTag>;
    onSeekedCapture?: React.ReactEventHandler<TTag>;
    onSeeking?: React.ReactEventHandler<TTag>;
    onSeekingCapture?: React.ReactEventHandler<TTag>;
    onStalled?: React.ReactEventHandler<TTag>;
    onStalledCapture?: React.ReactEventHandler<TTag>;
    onSuspend?: React.ReactEventHandler<TTag>;
    onSuspendCapture?: React.ReactEventHandler<TTag>;
    onTimeUpdate?: React.ReactEventHandler<TTag>;
    onTimeUpdateCapture?: React.ReactEventHandler<TTag>;
    onVolumeChange?: React.ReactEventHandler<TTag>;
    onVolumeChangeCapture?: React.ReactEventHandler<TTag>;
    onWaiting?: React.ReactEventHandler<TTag>;
    onWaitingCapture?: React.ReactEventHandler<TTag>;
    onAuxClick?: React.MouseEventHandler<TTag>;
    onAuxClickCapture?: React.MouseEventHandler<TTag>;
    onClick?: React.MouseEventHandler<TTag>;
    onClickCapture?: React.MouseEventHandler<TTag>;
    onContextMenu?: React.MouseEventHandler<TTag>;
    onContextMenuCapture?: React.MouseEventHandler<TTag>;
    onDoubleClick?: React.MouseEventHandler<TTag>;
    onDoubleClickCapture?: React.MouseEventHandler<TTag>;
    onDrag?: React.DragEventHandler<TTag>;
    onDragCapture?: React.DragEventHandler<TTag>;
    onDragEnd?: React.DragEventHandler<TTag>;
    onDragEndCapture?: React.DragEventHandler<TTag>;
    onDragEnter?: React.DragEventHandler<TTag>;
    onDragEnterCapture?: React.DragEventHandler<TTag>;
    onDragExit?: React.DragEventHandler<TTag>;
    onDragExitCapture?: React.DragEventHandler<TTag>;
    onDragLeave?: React.DragEventHandler<TTag>;
    onDragLeaveCapture?: React.DragEventHandler<TTag>;
    onDragOver?: React.DragEventHandler<TTag>;
    onDragOverCapture?: React.DragEventHandler<TTag>;
    onDragStart?: React.DragEventHandler<TTag>;
    onDragStartCapture?: React.DragEventHandler<TTag>;
    onDrop?: React.DragEventHandler<TTag>;
    onDropCapture?: React.DragEventHandler<TTag>;
    onMouseDown?: React.MouseEventHandler<TTag>;
    onMouseDownCapture?: React.MouseEventHandler<TTag>;
    onMouseEnter?: React.MouseEventHandler<TTag>;
    onMouseLeave?: React.MouseEventHandler<TTag>;
    onMouseMove?: React.MouseEventHandler<TTag>;
    onMouseMoveCapture?: React.MouseEventHandler<TTag>;
    onMouseOut?: React.MouseEventHandler<TTag>;
    onMouseOutCapture?: React.MouseEventHandler<TTag>;
    onMouseOver?: React.MouseEventHandler<TTag>;
    onMouseOverCapture?: React.MouseEventHandler<TTag>;
    onMouseUp?: React.MouseEventHandler<TTag>;
    onMouseUpCapture?: React.MouseEventHandler<TTag>;
    onSelect?: React.ReactEventHandler<TTag>;
    onSelectCapture?: React.ReactEventHandler<TTag>;
    onTouchCancel?: React.TouchEventHandler<TTag>;
    onTouchCancelCapture?: React.TouchEventHandler<TTag>;
    onTouchEnd?: React.TouchEventHandler<TTag>;
    onTouchEndCapture?: React.TouchEventHandler<TTag>;
    onTouchMove?: React.TouchEventHandler<TTag>;
    onTouchMoveCapture?: React.TouchEventHandler<TTag>;
    onTouchStart?: React.TouchEventHandler<TTag>;
    onTouchStartCapture?: React.TouchEventHandler<TTag>;
    onPointerDown?: React.PointerEventHandler<TTag>;
    onPointerDownCapture?: React.PointerEventHandler<TTag>;
    onPointerMove?: React.PointerEventHandler<TTag>;
    onPointerMoveCapture?: React.PointerEventHandler<TTag>;
    onPointerUp?: React.PointerEventHandler<TTag>;
    onPointerUpCapture?: React.PointerEventHandler<TTag>;
    onPointerCancel?: React.PointerEventHandler<TTag>;
    onPointerCancelCapture?: React.PointerEventHandler<TTag>;
    onPointerEnter?: React.PointerEventHandler<TTag>;
    onPointerLeave?: React.PointerEventHandler<TTag>;
    onPointerOver?: React.PointerEventHandler<TTag>;
    onPointerOverCapture?: React.PointerEventHandler<TTag>;
    onPointerOut?: React.PointerEventHandler<TTag>;
    onPointerOutCapture?: React.PointerEventHandler<TTag>;
    onGotPointerCapture?: React.PointerEventHandler<TTag>;
    onGotPointerCaptureCapture?: React.PointerEventHandler<TTag>;
    onLostPointerCapture?: React.PointerEventHandler<TTag>;
    onLostPointerCaptureCapture?: React.PointerEventHandler<TTag>;
    onScroll?: React.UIEventHandler<TTag>;
    onScrollCapture?: React.UIEventHandler<TTag>;
    onWheel?: React.WheelEventHandler<TTag>;
    onWheelCapture?: React.WheelEventHandler<TTag>;
    onAnimationStart?: React.AnimationEventHandler<TTag>;
    onAnimationStartCapture?: React.AnimationEventHandler<TTag>;
    onAnimationEnd?: React.AnimationEventHandler<TTag>;
    onAnimationEndCapture?: React.AnimationEventHandler<TTag>;
    onAnimationIteration?: React.AnimationEventHandler<TTag>;
    onAnimationIterationCapture?: React.AnimationEventHandler<TTag>;
    onTransitionEnd?: React.TransitionEventHandler<TTag>;
    onTransitionEndCapture?: React.TransitionEventHandler<TTag>;
} | {
    ref: React.MutableRefObject<HTMLElement>;
    defaultChecked?: boolean;
    defaultValue?: string | number | readonly string[];
    suppressContentEditableWarning?: boolean;
    suppressHydrationWarning?: boolean;
    accessKey?: string;
    autoCapitalize?: "none" | (string & {}) | "words" | "off" | "on" | "sentences" | "characters";
    autoFocus?: boolean;
    className?: string;
    contentEditable?: "inherit" | (boolean | "false" | "true") | "plaintext-only";
    contextMenu?: string;
    dir?: string;
    draggable?: boolean | "false" | "true";
    enterKeyHint?: "search" | "next" | "done" | "enter" | "go" | "previous" | "send";
    hidden?: boolean;
    id?: string;
    lang?: string;
    nonce?: string;
    slot?: string;
    spellCheck?: boolean | "false" | "true";
    style?: React.CSSProperties;
    tabIndex?: number;
    title?: string;
    translate?: "yes" | "no";
    radioGroup?: string;
    role?: React.AriaRole;
    about?: string;
    content?: string;
    datatype?: string;
    inlist?: any;
    prefix?: string;
    property?: string;
    rel?: string;
    resource?: string;
    rev?: string;
    typeof?: string;
    vocab?: string;
    autoCorrect?: string;
    autoSave?: string;
    color?: string;
    itemProp?: string;
    itemScope?: boolean;
    itemType?: string;
    itemID?: string;
    itemRef?: string;
    results?: number;
    security?: string;
    unselectable?: "off" | "on";
    inputMode?: "search" | "numeric" | "none" | "url" | "text" | "decimal" | "tel" | "email";
    is?: string;
    exportparts?: string;
    part?: string;
    "aria-activedescendant"?: string;
    "aria-atomic"?: boolean | "false" | "true";
    "aria-autocomplete"?: "inline" | "both" | "none" | "list";
    "aria-braillelabel"?: string;
    "aria-brailleroledescription"?: string;
    "aria-busy"?: boolean | "false" | "true";
    "aria-checked"?: boolean | "false" | "mixed" | "true";
    "aria-colcount"?: number;
    "aria-colindex"?: number;
    "aria-colindextext"?: string;
    "aria-colspan"?: number;
    "aria-controls"?: string;
    "aria-current"?: boolean | "location" | "time" | "false" | "page" | "true" | "step" | "date";
    "aria-describedby"?: string;
    "aria-description"?: string;
    "aria-details"?: string;
    "aria-disabled"?: boolean | "false" | "true";
    "aria-dropeffect"?: "link" | "none" | "copy" | "move" | "execute" | "popup";
    "aria-errormessage"?: string;
    "aria-expanded"?: boolean | "false" | "true";
    "aria-flowto"?: string;
    "aria-grabbed"?: boolean | "false" | "true";
    "aria-haspopup"?: boolean | "grid" | "dialog" | "menu" | "false" | "listbox" | "true" | "tree";
    "aria-hidden"?: boolean | "false" | "true";
    "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling";
    "aria-keyshortcuts"?: string;
    "aria-label"?: string;
    "aria-labelledby"?: string;
    "aria-level"?: number;
    "aria-live"?: "off" | "assertive" | "polite";
    "aria-modal"?: boolean | "false" | "true";
    "aria-multiline"?: boolean | "false" | "true";
    "aria-multiselectable"?: boolean | "false" | "true";
    "aria-orientation"?: "horizontal" | "vertical";
    "aria-owns"?: string;
    "aria-placeholder"?: string;
    "aria-posinset"?: number;
    "aria-pressed"?: boolean | "false" | "mixed" | "true";
    "aria-readonly"?: boolean | "false" | "true";
    "aria-relevant"?: "all" | "text" | "additions" | "additions removals" | "additions text" | "removals" | "removals additions" | "removals text" | "text additions" | "text removals";
    "aria-required"?: boolean | "false" | "true";
    "aria-roledescription"?: string;
    "aria-rowcount"?: number;
    "aria-rowindex"?: number;
    "aria-rowindextext"?: string;
    "aria-rowspan"?: number;
    "aria-selected"?: boolean | "false" | "true";
    "aria-setsize"?: number;
    "aria-sort"?: "none" | "other" | "ascending" | "descending";
    "aria-valuemax"?: number;
    "aria-valuemin"?: number;
    "aria-valuenow"?: number;
    "aria-valuetext"?: string;
    dangerouslySetInnerHTML?: {
        __html: string | TrustedHTML;
    };
    onCopy?: React.ClipboardEventHandler<TTag>;
    onCopyCapture?: React.ClipboardEventHandler<TTag>;
    onCut?: React.ClipboardEventHandler<TTag>;
    onCutCapture?: React.ClipboardEventHandler<TTag>;
    onPaste?: React.ClipboardEventHandler<TTag>;
    onPasteCapture?: React.ClipboardEventHandler<TTag>;
    onCompositionEnd?: React.CompositionEventHandler<TTag>;
    onCompositionEndCapture?: React.CompositionEventHandler<TTag>;
    onCompositionStart?: React.CompositionEventHandler<TTag>;
    onCompositionStartCapture?: React.CompositionEventHandler<TTag>;
    onCompositionUpdate?: React.CompositionEventHandler<TTag>;
    onCompositionUpdateCapture?: React.CompositionEventHandler<TTag>;
    onFocus?: React.FocusEventHandler<TTag>;
    onFocusCapture?: React.FocusEventHandler<TTag>;
    onBlur?: React.FocusEventHandler<TTag>;
    onBlurCapture?: React.FocusEventHandler<TTag>;
    onChange?: React.FormEventHandler<TTag>;
    onChangeCapture?: React.FormEventHandler<TTag>;
    onBeforeInput?: React.InputEventHandler<TTag>;
    onBeforeInputCapture?: React.FormEventHandler<TTag>;
    onInput?: React.FormEventHandler<TTag>;
    onInputCapture?: React.FormEventHandler<TTag>;
    onReset?: React.FormEventHandler<TTag>;
    onResetCapture?: React.FormEventHandler<TTag>;
    onSubmit?: React.FormEventHandler<TTag>;
    onSubmitCapture?: React.FormEventHandler<TTag>;
    onInvalid?: React.FormEventHandler<TTag>;
    onInvalidCapture?: React.FormEventHandler<TTag>;
    onLoad?: React.ReactEventHandler<TTag>;
    onLoadCapture?: React.ReactEventHandler<TTag>;
    onError?: React.ReactEventHandler<TTag>;
    onErrorCapture?: React.ReactEventHandler<TTag>;
    onKeyDown?: React.KeyboardEventHandler<TTag>;
    onKeyDownCapture?: React.KeyboardEventHandler<TTag>;
    onKeyPress?: React.KeyboardEventHandler<TTag>;
    onKeyPressCapture?: React.KeyboardEventHandler<TTag>;
    onKeyUp?: React.KeyboardEventHandler<TTag>;
    onKeyUpCapture?: React.KeyboardEventHandler<TTag>;
    onAbort?: React.ReactEventHandler<TTag>;
    onAbortCapture?: React.ReactEventHandler<TTag>;
    onCanPlay?: React.ReactEventHandler<TTag>;
    onCanPlayCapture?: React.ReactEventHandler<TTag>;
    onCanPlayThrough?: React.ReactEventHandler<TTag>;
    onCanPlayThroughCapture?: React.ReactEventHandler<TTag>;
    onDurationChange?: React.ReactEventHandler<TTag>;
    onDurationChangeCapture?: React.ReactEventHandler<TTag>;
    onEmptied?: React.ReactEventHandler<TTag>;
    onEmptiedCapture?: React.ReactEventHandler<TTag>;
    onEncrypted?: React.ReactEventHandler<TTag>;
    onEncryptedCapture?: React.ReactEventHandler<TTag>;
    onEnded?: React.ReactEventHandler<TTag>;
    onEndedCapture?: React.ReactEventHandler<TTag>;
    onLoadedData?: React.ReactEventHandler<TTag>;
    onLoadedDataCapture?: React.ReactEventHandler<TTag>;
    onLoadedMetadata?: React.ReactEventHandler<TTag>;
    onLoadedMetadataCapture?: React.ReactEventHandler<TTag>;
    onLoadStart?: React.ReactEventHandler<TTag>;
    onLoadStartCapture?: React.ReactEventHandler<TTag>;
    onPause?: React.ReactEventHandler<TTag>;
    onPauseCapture?: React.ReactEventHandler<TTag>;
    onPlay?: React.ReactEventHandler<TTag>;
    onPlayCapture?: React.ReactEventHandler<TTag>;
    onPlaying?: React.ReactEventHandler<TTag>;
    onPlayingCapture?: React.ReactEventHandler<TTag>;
    onProgress?: React.ReactEventHandler<TTag>;
    onProgressCapture?: React.ReactEventHandler<TTag>;
    onRateChange?: React.ReactEventHandler<TTag>;
    onRateChangeCapture?: React.ReactEventHandler<TTag>;
    onSeeked?: React.ReactEventHandler<TTag>;
    onSeekedCapture?: React.ReactEventHandler<TTag>;
    onSeeking?: React.ReactEventHandler<TTag>;
    onSeekingCapture?: React.ReactEventHandler<TTag>;
    onStalled?: React.ReactEventHandler<TTag>;
    onStalledCapture?: React.ReactEventHandler<TTag>;
    onSuspend?: React.ReactEventHandler<TTag>;
    onSuspendCapture?: React.ReactEventHandler<TTag>;
    onTimeUpdate?: React.ReactEventHandler<TTag>;
    onTimeUpdateCapture?: React.ReactEventHandler<TTag>;
    onVolumeChange?: React.ReactEventHandler<TTag>;
    onVolumeChangeCapture?: React.ReactEventHandler<TTag>;
    onWaiting?: React.ReactEventHandler<TTag>;
    onWaitingCapture?: React.ReactEventHandler<TTag>;
    onAuxClick?: React.MouseEventHandler<TTag>;
    onAuxClickCapture?: React.MouseEventHandler<TTag>;
    onClick?: React.MouseEventHandler<TTag>;
    onClickCapture?: React.MouseEventHandler<TTag>;
    onContextMenu?: React.MouseEventHandler<TTag>;
    onContextMenuCapture?: React.MouseEventHandler<TTag>;
    onDoubleClick?: React.MouseEventHandler<TTag>;
    onDoubleClickCapture?: React.MouseEventHandler<TTag>;
    onDrag?: React.DragEventHandler<TTag>;
    onDragCapture?: React.DragEventHandler<TTag>;
    onDragEnd?: React.DragEventHandler<TTag>;
    onDragEndCapture?: React.DragEventHandler<TTag>;
    onDragEnter?: React.DragEventHandler<TTag>;
    onDragEnterCapture?: React.DragEventHandler<TTag>;
    onDragExit?: React.DragEventHandler<TTag>;
    onDragExitCapture?: React.DragEventHandler<TTag>;
    onDragLeave?: React.DragEventHandler<TTag>;
    onDragLeaveCapture?: React.DragEventHandler<TTag>;
    onDragOver?: React.DragEventHandler<TTag>;
    onDragOverCapture?: React.DragEventHandler<TTag>;
    onDragStart?: React.DragEventHandler<TTag>;
    onDragStartCapture?: React.DragEventHandler<TTag>;
    onDrop?: React.DragEventHandler<TTag>;
    onDropCapture?: React.DragEventHandler<TTag>;
    onMouseDown: ((e: React.MouseEvent<HTMLElement, MouseEvent>) => void) | React.MouseEventHandler<TTag>;
    onMouseDownCapture?: React.MouseEventHandler<TTag>;
    onMouseEnter?: React.MouseEventHandler<TTag>;
    onMouseLeave?: React.MouseEventHandler<TTag>;
    onMouseMove?: React.MouseEventHandler<TTag>;
    onMouseMoveCapture?: React.MouseEventHandler<TTag>;
    onMouseOut?: React.MouseEventHandler<TTag>;
    onMouseOutCapture?: React.MouseEventHandler<TTag>;
    onMouseOver?: React.MouseEventHandler<TTag>;
    onMouseOverCapture?: React.MouseEventHandler<TTag>;
    onMouseUp?: React.MouseEventHandler<TTag>;
    onMouseUpCapture?: React.MouseEventHandler<TTag>;
    onSelect?: React.ReactEventHandler<TTag>;
    onSelectCapture?: React.ReactEventHandler<TTag>;
    onTouchCancel?: React.TouchEventHandler<TTag>;
    onTouchCancelCapture?: React.TouchEventHandler<TTag>;
    onTouchEnd?: React.TouchEventHandler<TTag>;
    onTouchEndCapture?: React.TouchEventHandler<TTag>;
    onTouchMove?: React.TouchEventHandler<TTag>;
    onTouchMoveCapture?: React.TouchEventHandler<TTag>;
    onTouchStart?: React.TouchEventHandler<TTag>;
    onTouchStartCapture?: React.TouchEventHandler<TTag>;
    onPointerDown?: React.PointerEventHandler<TTag>;
    onPointerDownCapture?: React.PointerEventHandler<TTag>;
    onPointerMove?: React.PointerEventHandler<TTag>;
    onPointerMoveCapture?: React.PointerEventHandler<TTag>;
    onPointerUp?: React.PointerEventHandler<TTag>;
    onPointerUpCapture?: React.PointerEventHandler<TTag>;
    onPointerCancel?: React.PointerEventHandler<TTag>;
    onPointerCancelCapture?: React.PointerEventHandler<TTag>;
    onPointerEnter?: React.PointerEventHandler<TTag>;
    onPointerLeave?: React.PointerEventHandler<TTag>;
    onPointerOver?: React.PointerEventHandler<TTag>;
    onPointerOverCapture?: React.PointerEventHandler<TTag>;
    onPointerOut?: React.PointerEventHandler<TTag>;
    onPointerOutCapture?: React.PointerEventHandler<TTag>;
    onGotPointerCapture?: React.PointerEventHandler<TTag>;
    onGotPointerCaptureCapture?: React.PointerEventHandler<TTag>;
    onLostPointerCapture?: React.PointerEventHandler<TTag>;
    onLostPointerCaptureCapture?: React.PointerEventHandler<TTag>;
    onScroll?: React.UIEventHandler<TTag>;
    onScrollCapture?: React.UIEventHandler<TTag>;
    onWheel?: React.WheelEventHandler<TTag>;
    onWheelCapture?: React.WheelEventHandler<TTag>;
    onAnimationStart?: React.AnimationEventHandler<TTag>;
    onAnimationStartCapture?: React.AnimationEventHandler<TTag>;
    onAnimationEnd?: React.AnimationEventHandler<TTag>;
    onAnimationEndCapture?: React.AnimationEventHandler<TTag>;
    onAnimationIteration?: React.AnimationEventHandler<TTag>;
    onAnimationIterationCapture?: React.AnimationEventHandler<TTag>;
    onTransitionEnd?: React.TransitionEventHandler<TTag>;
    onTransitionEndCapture?: React.TransitionEventHandler<TTag>;
}, string | React.JSXElementConstructor<any>>;
type ItemProps = {
    children: React.ReactElement;
};
/**
 * SortableItem only adds a ref to its children so that we can register it to the main Sortable
 */
export declare const SortableItem: ({ children }: ItemProps) => React.ReactElement<any, string | React.JSXElementConstructor<any>>;
export declare const SortableKnob: ({ children }: ItemProps) => React.ReactElement<any, string | React.JSXElementConstructor<any>>;
export default SortableList;
